project:
  type: book
book:
  title: אלגברה לינארית
  author: ד"ר יונתן שלח, ד"ר נדב מאיר
  language: he
  chapters:
  - index.qmd
  - intro.qmd
  - chapter_0.qmd
  - chapter_0_5.qmd
  - chapter_1.qmd
  - chapter_2.qmd
  # - chapter_3.qmd
  # - chapter_calculus.qmd
  - summary.qmd
  - references.qmd
  search: true
  
  
  sidebar:
    tools:
    - icon: download
      href: אלגברה-לינארית.pdf
      text: הורדת הספר כ-PDF
    logo: logo.png
bibliography: references.bib

crossref:
  chapters: true



format:
  html:
    toc: true
    number-sections: true
    html-math-method: katex
    fig-align: center
    fig-cap-location: bottom

    callout:
      collapse: true
    css: 
      - rtl-baseline.css
      - styles.css
    include-after-body:
      - auto-env-titles.html
      - chapter-numbering.html
      
    filters:
      - env-to-callout.lua
    theorems:
      numbering: true
      within: chapter        # מספור בתוך פרק: 1.1, 1.2, ...; 2.1, 2.2, ...
      definition:
        name: "הגדרה"
      example:
        name: "דוגמה"
      exercise:
        name: "תרגיל"
      remark:
        name: "הערה"
      theorem:
        name: "משפט"
      lemma:
        name: "למה"
      proposition:
        name: "טענה"
      corollary:
        name: "מסקנה"
      proof:
        name: "הוכחה"
        numbering: false     # הוכחות בלי מספור   
 
        
number-sections: true



resources:
  - simulations/**
  - images/**