project:
  type: book
book:
  title: אלגברה לינארית
  author: ד"ר יונתן שלח, ד"ר נדב מאיר
  language: he
  chapters:
  - index.qmd
  - intro.qmd      #chapter 0 introduction
  - chapter_0.qmd   #chpater 1 preliminaries
  - chapter_0_5.qmd  #chapter 2 Complex Numbers
  - chapter_1.qmd    #chapter 3 geometry of linear equations
  - chapter_2.qmd    #chapter 4 Systems of Linear Equations
  - chapter_3.qmd    #chapter 5 Matrices
  - chapter_4.qmd    #chapter 6 Determinants
  - chapter_5.qmd    #chapter 7 Vector Spaces
  - chapter_6.qmd    #chapter 8 subspaces
 # - summary.qmd
  - references.qmd
  search: true
  sidebar:
    logo: logo.png
    tools:
      - icon: download
        href: אלגברה-לינארית.pdf
        text: הורדת הספר כ-PDF

language:
  label:
    fig: "איור"
    tbl: "טבלה"
    eq: "משוואה"
  ui:
    chapter: "פרק"
bibliography: references.bib

crossref:
  chapters: true
  fig-title: "איור"     # במקום "Figure" בכיתובי איורים
  fig-prefix: "איור"    # במקום "Figure" בטקסטי הפניה (@fig-...)
  tbl-title: "טבלה"
  tbl-prefix: "טבלה"
  title-delim: ":"      # המפריד בין "איור 4.1" לכיתוב (לא תמיד חל ב-PDF)


format:
  html:
    toc: true
    number-sections: true
    html-math-method: mathjax
    fig-align: center
    fig-cap-location: bottom

    callout:
      collapse: true
    css: 
      - rtl-baseline.css
      - styles.css
    include-before-body:
      - math-macros.html
    include-after-body:
      - auto-env-titles.html
      - chapter-numbering.html
      - tracking.html
      - report-typo.html   # ← זה
    include-in-header: _includes/head.html
      
    filters:
      - env-to-callout.lua
    theorems:
      numbering: true
      within: chapter        # מספור בתוך פרק: 1.1, 1.2, ...; 2.1, 2.2, ...
      definition:
        name: "הגדרה"
      example:
        name: "דוגמה"
      exercise:
        name: "תרגיל"
      remark:
        name: "הערה"
      theorem:
        name: "משפט"
      lemma:
        name: "למה"
      proposition:
        name: "טענה"
      corollary:
        name: "מסקנה"
      proof:
        name: "הוכחה"
        numbering: false     # הוכחות בלי מספור
      solution:
        name: "פתרון"


number-sections: true

website:
  google-analytics: "G-TPY4VZJV6M"


resources:
  - simulations/**
  - images/**
  - downloads/**