project:
  type: book

book:
  title: "אלגברה לינארית"
  author: "ד\"ר יונתן שלח, ד\"ר נדב מאיר"
  language: he
  chapters:
    - index.qmd
    - intro.qmd
    - chapter_0.qmd
    - chapter_0_5.qmd
    - chapter_1.qmd
    - chapter_2.qmd
    - chapter_3.qmd
    - summary.qmd
    - references.qmd

  sidebar:
    tools:
      - icon: download
        href: "אלגברה-לינארית.pdf" 
        text: "הורדת הספר כ-PDF"
  # -------------------------
bibliography: references.bib

format:
  html:
    theme: cosmo
    toc: true
    number-sections: true
    css: styles.css
    html-math-method: katex
    fig-align: center
    fig-cap-location: bottom
    callout:
      collapse: true

  pdf:
    documentclass: book
    papersize: a4
    classoption: oneside
    lang: he
    toc: true
    number-sections: true
    mainfont: "David"         # או "Frank Ruehl CLM", "Noto Sans Hebrew"
    monofont: "Courier New"
    fontsize: 12pt
    linestretch: 1.5
    geometry: "right=30mm, left=30mm, top=30mm, bottom=30mm"
    header-includes:
      - \usepackage{bidi}      # תמיכה בעברית
      - \setRTL                # כתיבה מימין לשמאל
  
filters:
  - uncollapse-for-pdf.lua
# --------------------

