# פרק חדוא

## סדרות

יתכן מאוד וכבר שמעתם על סדרות חשבוניות, לדוגמא, $1,2,3,4,5,\ldots$,
וסדרות הנדסיות, לדוגמא,
$1,\frac{1}{2},\frac{1}{4},\frac{1}{8},\frac{1}{16},\ldots$. אלה הן שתי
משפחות של סדרות של מספרים.

::: {.definition}
*סדרה של מספרים ממשיים* היא פונקציה $f$ אשר תחום הגדרתה הוא קבוצת
המספרים הטבעיים וטווחה הוא קבוצת המספרים הממשיים. נסכים לכתוב $a_n$
במקום $f(n)$.
:::

$$\begin{array}{cccccc}
1 & 2 & 3 & \ldots & n & \ldots \\
\downarrow & \downarrow & \downarrow & \downarrow & \downarrow & \downarrow \\
f(1) & f(2) & f(3) & \ldots & f(n) & \ldots
\end{array}$$

כמו לכל פונקציה, גם לסדרה יש הצגה גרפית. לכל מספר סידורי $n$ על ציר ה-
$x$ נתאים נקודה $(n,a_n)$. לדוגמא, הסדרה שמתוארת באיור היא
$a_n=\frac{1}{n}$.

::: center
:::

נהוג לסמן סדרה ע\"י $\{a_n\}_{n=1}^\infty$, כש- $a_{17}$ הוא האיבר ה-
$17$ שלה ו- $a_{129}$ הוא האיבר ה- $129$ שלה. לעתים בכתיבת איברי הסדרה
מוותרים על הסוגריים ורושמים פשוט $a_1,a_2,a_3,\ldots$.

::: {.example}
1. $\{n\}_{n=1}^\infty$ היא סדרה של מספרים טבעיים המופיעים לפי הסדר
   ה\"טבעי\" שלהם, כלומר, $$1,2,3,4,5,\ldots.$$

2. $\{2n-1\}_{n=1}^\infty$ היא סדרה של מספרים טבעיים אי-זוגיים, כלומר,
   $$1,3,5,7,9,\ldots.$$
:::

::: {.example}
הסדרה $a_n=1$ לכל $n$, כלומר $$1,1,1,1,1,\ldots.$$
:::

::: {.example}
$\{(-1)^n\}_{n=1}^\infty$ היא סדרה של מספרים $-1$ ו- $1$ המתחלפים,
כלומר, $$-1,1,-1,1,-1,\ldots.$$
:::

::: {.example}
$\left\{\frac{(-1)^{n+1}}{n}\right\}_{n=1}^\infty$ היא הסדרה הבאה
$$1,-\frac{1}{2},\frac{1}{3},-\frac{1}{4},\frac{1}{5},\ldots.$$
:::

קיימים אופנים שונים להגדרת סדרה. בכל אחת מהדוגמאות לעיל, סדרה הוגדרה
ע\"י נוסחא לחישוב איברה הכללי. זהו לא האופן היחיד. אחת השיטות הנפוצות
להגדרת סדרה היא השיטה *רקורסיבית* - השיטה שמאפשרת חישוב של איברה הכללי
של סדרה דרך האיברים הקודמים. בשיטה זאת נחוצים *תנאיי התחלה*. לדוגמא, תהא
$\{a_n\}_{n=1}^\infty$ מוגדרת ע\"י $a_{n}=a_{n-2}+a_{n-1}$ כאשר $a_1=1$
ו- $a_2=1$. )שימו לב כי סדרות רקורסיביות עם נוסחת נסיגה זהה שנבדלות
בתנאיי התחילה הן סדרות שונות.( לא קשה להשתכנע כי איבריה הראשונים של
הסדרה הם $1,1,2,3,5,8,13,21,\ldots$. קיימת גם נוסחא לחישוב של איברה
הכללי של הסדרה הזאת
$$a_n=\frac{(1+\sqrt{5})^n-(1-\sqrt{5})^n}{2^n\sqrt{5}}.$$ זאת סדרה
\"ידוענית\" בתחום המתמטיקה, היא נקראת *סדרת פיבונצ'י*, על כינויו של
מתמטיקאי איטלקי מימי הביניים- לאונרדו פיזנו.

::: {.theorem}
אם $a > b$ ו־$b > c$, אז $a > c$.
:::
