# מערכות משוואות לינאריות

בפרק הקודם עסקנו במשוואות לינאריות עם שני משתנים Ł$x,y$ לתיאור המישור, וגם בשלושה משתנים Ł$x,y,z$ לתיאור המרחב. אנחנו רוצים להכליל את הדיון למספר כלשהו Ł$n$ )טבעי( של משתנים, לאו דווקא בעלי משמעות גיאומטרית. מהי המוטיבציה? משוואות לינאריות מופיעות בפיזיקה כבר בחוק השני של ניוטון לפיו יש תלות לינארית בין וקטור הכוח הפועל על גוף לבין לוקטור התאוצה של הגוף. כאשר יש הרבה גופים בבעיה עם תלות ביניהם )אילוצים(, יכולות להתקבל מספר משוואות לינאריות במספר משתנים ויחד הן נקראות מערכת משוואות לינאריות. זה המקרה גם בתחומים רבים אחרים, כמו למשל רשתות נוירונים בהן כל נוירון מקבל קלטים ומפיק מהם פלט לפי חישוב שמתאים למשוואה לינארית.

תחילה נבהיר איך נראית משוואה לינארית במספר משתנים )ייתכן גדול מאוד( ואיך מחשבים את קבוצת הפתרונות שלה.

### משוואה לינארית במספר משתנים

איך נראית משוואה לינארית כללית? נשתמש במשתנים Ł$x_{1},x_{2,}...,x_{n}$ במקום אותיות רגילות, כי לצורך העניין Ł$n$ יכול להיות גדול בהרבה ממספר האותיות באלף בית הלועזי )Ł$26$( או בכל שפה אחרת. גם נראה בהמשך שצריך לבחור איזשהו סדר בין המשתנים, אז אם מספרם גדול זה נוח להשתמש באינדקס מספרי כדי להדגיש את הסדר ביניהם.

::: {.definition}
משוואה לינארית במשתנים \L{$x_{1},x_{2,}...,x_{n}$} היא משוואה
מהצורה \L{%
\[
(*)\:a_{1}x_{1}+a_{2}x_{2}+a_{3}x_{3}+...+a_{n}x_{n}=b
\]
}%

כאשר \L{$a_{1},...,a_{n}$} הם סקלרים נתונים שנקראים מקדמים, ו-\L{$b$}
הוא סקלר נתון שנקרא קבוע או איבר חופשי. אם כל הסקלרים והמשתנים ממשיים,
נאמר שזו משוואה לינארית מעל \L{$\mathbb{\mathbb{R}}$}. אם לפחות סקלר
אחד הוא מרוכב ו/או המשתנים מרוכבים, נאמר שזו משוואה לינארית מעל \L{$\mathbb{C}$}.
אם נרצה להכליל בלי לציין שמדובר ב-\L{$\mathbb{R}$} או \L{$\mathbb{\mathbb{C}}$},
נכתוב \L{$\mathbb{F}$} ונזכור שקבוצה זו היא או \L{$\mathbb{R}$}
או \L{$\mathbb{C}$}.
:::
::: {.example}
א. \L{$x_{1}-x_{2}+x_{3}-x_{4}=100$} זו משוואה לינארית בארבעה
משתנים מעל \L{$\mathbb{R}$}.

ב. \L{$x_{1}+ix_{2}-x_{3}-ix_{4}+x_{5}=1+i$} זו משוואה לינארית בחמישה
משתנים מעל \L{$\mathbb{C}$}.
:::
::: {.definition}
סדרת סקלרים \L{$(c_{1},c_{2},...,c_{n})$} נקראת \L{$n$}-יה,
או וקטור באורך \L{$n$}. נגדיר את מרחב ה-\L{$n$}-יות מעל \L{$\mathbb{\mathbb{R}}$}:\L{%
\[
\mathbb{R}^{n}=\{(c_{1},c_{2},....,c_{n})|c_{1},c_{2},....,c_{n}\in\mathbb{R}\}
\]
}%
 וגם את מרחב ה-\L{$n$}-יות מעל \L{$\mathbb{\mathbb{C}}$}:\L{%
\[
\mathbb{\mathbb{C}}^{n}=\{(c_{1},c_{2},....,c_{n})|c_{1},c_{2},....,c_{n}\in\mathbb{\mathbb{C}}\}
\]
}%

לעיתים נכתוב \L{$\mathbb{F}^{n}$} במקום לפרט אם הכוונה היא ל-\L{$\mathbb{R}^{n}$}
או ל-\L{$\mathbb{C}^{n}$}.
:::

יש לנו אינטואיציה גיאומטרית טובה לגבי המישור הדו-מימדי Ł$\mathbb{R}^{2}$ והמרחב התלת-מימדי Ł$\mathbb{R}^{3}$. החל מ-Ł$\mathbb{R}^{4}$ ו-Ł$\mathbb{C}^{2}$ כבר אין לנו יכולת לדמיין את המרחבים האלה באופן מלא, אבל נתרגל גם אליהם מבחינה אלגברית.

::: {.definition}
פתרון של משוואה לינארית הינו \L{$n$}-יה \L{$(c_{1},c_{2},...,c_{n})\in\mathbb{F}^{n}$}
כך שבהצבת \L{%
\[
x_{1}=c_{1},x_{2}=c_{2},...,x_{n}=c_{n}
\]
}%

המשוואה מתקיימת.
:::
::: {.example}
א. משוואה לינארית ב-\L{$5$} משתנים מעל \L{$\mathbb{R}$}:
\L{%
\[
x_{1}+x_{2}+x_{3}+x_{4}+x_{5}=100
\]
}%

אחד הפתרונות של המשוואה הוא \L{$(x_{1},x_{2},x_{3},x_{4},x_{5})=(20,20,20,20,20)$}.
פתרון נוסף הוא \L{$(x_{1},x_{2},x_{3},x_{4},x_{5})=(50,10,10,10,10)$},
ויש עוד אינסוף אחרים. לעומת זאת, \L{$(x_{1},x_{2},x_{3},x_{4})=(0,0,0,0,0)$}
אינו פתרון כי ההצבה נותנת \L{$0=100$} וזה כמובן לא מתקיים.

כדי למצוא את קבוצת כל הפתרונות נבודד את אחד המשתנים. נוח לבחור את
\L{$x_{1}$} כי הוא הראשון. נקבל\L{%
\[
x_{1}=100-x_{2}-x_{3}-x_{4}-x_{5}
\]
}%

זה למעשה מראה שניתן לבחור את ערכיהם של \L{$x_{2},x_{3},x_{4},x_{5}$}
באופן שרירותי. זו משוואה מעל \L{$\mathbb{R}$} ולכן נבחר \L{$c_{2},c_{3},c_{4},c_{5}\in\mathbb{R}$}
שרירותיים ונציב \L{$(x_{2},x_{3},x_{4},x_{5})=(c_{2},c_{3},c_{4},c_{5})$}
במשוואה. כך נקבל\L{%
\[
.x_{1}=100-c_{2}-c_{3}-c_{4}-c_{5}
\]
}%

לכן, קבוצת הפתרונות נתונה באופן פרמטרי )עם {\beginL 4\endL} פרמטרים
\L{$c_{2},c_{3},c_{4},c_{5}$}( ע\textquotedbl י\L{%
\[
.\{100-c_{2}-c_{3}-c_{4}-c_{5},c_{2},c_{3},c_{4},c_{5})|c_{2},c_{3},c_{4},c_{5}\in\mathbb{R}\}
\]
}%

ב. משוואה לינארית ב-\L{$4$} משתנים מעל \L{$\mathbb{\mathbb{C}}$}:
\L{%
\[
x_{1}+ix_{2}+2ix_{3}+x_{4}=1+4i
\]
}%

אחד הפתרונות של המשוואה הוא \L{$(x_{1},x_{2},x_{3},x_{4})=(1,1,1,i)$}
ויש עוד אינסוף אחרים. \L{$(x_{1},x_{2},x_{3},x_{4})=(1,0,1,0)$} אינו
פתרון כי \L{$1+2i\neq1+4i$}.

נבודד את \L{$x_{1}$} כדי למצוא את קבוצת הפתרונות:\L{%
\[
x_{1}=1+4i-ix_{2}-2ix_{3}-x_{4}
\]
}%

זו משוואה מעל \L{$\mathbb{\mathbb{C}}$} ולכן נבחר \L{$c_{2},c_{3},c_{4}\in\mathbb{C}$}
שרירותיים ונציב אותם במשוואה. כך נקבל\L{%
\[
.x_{1}=1+4i-ic_{2}-2ic_{3}-c_{4}
\]
}%

לכן, קבוצת הפתרונות נתונה באופן פרמטרי )עם {\beginL 3\endL} פרמטרים
\L{$c_{2},c_{3},c_{4}$}( ע\textquotedbl י\L{%
\[
.\{1+4i-ic_{2}-2ic_{3}-c_{4},c_{2},c_{3},c_{4})|c_{2},c_{3},c_{4}\in\mathbb{\mathbb{C}}\}
\]
}%
:::

איך פותרים משוואה לינארית כללית מהצורה Ł$(*)$? אפשר למצוא את כל הפתרונות ע`\textquotedbl `{=latex}י בידוד אחד המשתנים. מקובל לעשות זאת עבור Ł$x_{1}$ בהנחה ש-Ł$a_{1}\neq0$ )אם Ł$a_{1}=0$, נבחר את המשתנה הראשון עם מקדם השונה מ-Ł$0$( וכך לקבלŁ $$.x_{1}=\frac{1}{a_{1}}(b-a_{2}x_{2}-a_{3}x_{3}-...-a_{n}x_{n})$$

זה מראה שלכל בחירה של סקלרים Ł$c_{2},....,c_{n}\in\mathbb{F}$ נקבל פתרוןŁ $$.(x_{1},x_{2},x_{3},...,x_{n})=(\frac{1}{a_{1}}(b-a_{2}c_{2}-a_{3}c_{3}-...-a_{n}c_{n}),c_{2},c_{3},...,c_{n})$$

לכן, קבוצת הפתרונות של המשוואה נתונה בהצגה פרמטרית ע`\textquotedbl `{=latex}יŁ $$.\{(\frac{1}{a_{1}}(b-a_{2}c_{2}-a_{3}c_{3}-...-a_{n}c_{n}),c_{2},c_{3},...,c_{n})|c_{1},c_{2},...,c_{n}\in\mathbb{F}\}$$

נדגיש כי Ł$a_{1},a_{2},a_{3},...,a_{n}$ נתונים במשוואה כסקלרים קבועים. Ł$c_{1},c_{2},...,c_{n}$ הם פרמטרים שרצים על פני הקבוצה Ł$\mathbb{F}$ )Ł$\mathbb{R}$ או Ł$\mathbb{C}$( כדי לתאר את כל הפתרונות. זו הכללה של הצגה פרמטרית של ישר )פרמטר אחד( ושל מישור )שני פרמטרים( למספר כללי של פרמטרים, שהוא בעצם Ł$n-1$. בפרט, לכל Ł$n\geq2$ יש אינסוף פתרונות למשוואה Ł$(*)$ כי ניתן להציב אינסוף אפשרויות במשתנה אחד או יותר.

שימו לב שהתייחסנו אל Ł$x_{1}$ כמשתנה תלוי ואל Ł$x_{2},x_{3},...,x_{n}$ כמשתנים חופשיים )הצבנו בהם ערכים שרירותיים(. אם היינו מבודדים את Ł$x_{2}$ או משתנה אחר במקום Ł$x_{1}$, אז הוא היה המשתנה התלוי וההצגה הפרמטרית הייתה משתנה בהתאם. עדיין, זו רק הצגה חלופית לקבוצת הפתרונות של אותה המשוואה. טבעי לבחור את Ł$x_{1}$, אך אין חובה לעשות זאת.

::: {.exercise}
מצאו את קבוצת הפתרונות של המשוואה \L{$2x_{1}+x_{2}+3x_{3}+4x_{4}=5$}.
בדקו איך ההצגה הפרמטרית משתנה כאשר מבודדים את \L{$x_{2}$} במקום \L{$x_{1}$}.
:::

### מערכות משוואות לינאריות

בפרק הקודם ראינו הרבה דוגמאות למערכות משוואות לינאריות )ממ`\textquotedbl `{=latex}ל( מעל Ł$\mathbb{R}$ עם שתי משוואות בשני משתנים )לתיאור חיתוך שני ישרים במישור( וגם לממ`\textquotedbl `{=latex}ל עם שתי משוואות בשלושה משתנים )לתיאור חיתוך שני מישורים במרחב(. באופן כללי, אפשר להתייחס לכל אוסף של משוואות לינאריות כמערכת אחת.

בהקשר של החוק השני של ניוטון, אפשר לחשוב על ממ`\textquotedbl `{=latex}ל במספר גדול של משתנים שקשורים לוקטורי התאוצה של מספר גופים ולכוחות הפועלים עליהם. גם מספר המשתנים וגם מספר המשוואות יכולים להיות גדולים מאוד. אמנם גודל הממ`\textquotedbl `{=latex}ל מקשה על האינטואיציה הגיאומטרית ומוסיף חישובים )ייתכן באופן משמעותי(, אך עדיין יש גישה אלגברית אחת לפתרון של כל ממ`\textquotedbl `{=latex}ל. נפתח אותה בפרק זה.

::: {.example}
א. כל משוואה לינארית היא ממ\textquotedbl ל שבה משוואה אחת.
למשל: \L{%
\[
x_{1}+2x_{2}+3x_{3}+4x_{4}=5
\]
}%

זו ממ\textquotedbl ל של משוואה אחת בארבעה משתנים מעל \L{$\mathbb{R}$}. 

ב. ניקח את הדוגמה הקודמת ונוסיף משוואה:\L{%
\[
\begin{cases}
x_{1}+2x_{2}+3x_{3}+4x_{4}=5\\
x_{1}+x_{2}+x_{3}+x_{4}=4
\end{cases}
\]
}%

זו ממ\textquotedbl ל של שתי משוואות בארבעה משתנים מעל \L{$\mathbb{R}$}. 

ג. ממ\textquotedbl ל של שלוש משוואות בשלושה משתנים מעל \L{$\mathbb{\mathbb{R}}$}:\L{%
\[
\begin{cases}
x+y+z=3\\
x+2y+z=4\\
x+y+3z=5
\end{cases}
\]
}%
כאן חזרנו להשתמש באותיות המוכרות \L{$x,y,z$} במקום \L{$x_{1},x_{2},x_{3}$}.
הסימונים לא באמת חשובים כל עוד יש עקביות )נוח להשתמש באותיות רגילות
עבור מספר קטן של משתנים(. 

ד. ממ\textquotedbl ל של שתי משוואות בארבעה משתנים מעל \L{$\mathbb{C}$}:\L{%
\[
\begin{cases}
iz_{1}+z_{2}+iz_{3}+z_{4}=2i\\
z_{1}+(1+i)z_{2}+z_{2}+2iz_{3}=2
\end{cases}
\]
}%
:::
::: {.definition}
מערכת משוואות לינאריות )ממ\textquotedbl ל( במשתנים \L{$x_{1},x_{2,}...,x_{n}$}
היא אוסף של מספר כלשהו )\L{$m$}( של משוואות לינאריות מהצורה\L{%
\[
(**)\begin{cases}
a_{11}x_{1}+a_{12}x_{2}+a_{13}x_{3}+...+a_{1n}x_{n}=b_{1}\\
a_{21}x_{1}+a_{22}x_{2}+a_{23}x_{3}+...+a_{2n}x_{n}=b_{2}\\
a_{31}x_{1}+a_{32}x_{2}+a_{33}x_{3}+...+a_{3n}x_{n}=b_{3}\\
\qquad\qquad\qquad\qquad\quad\vdots\\
a_{n1}x_{1}+a_{n2}x_{2}+a_{n3}x_{3}+...+a_{nn}x_{n}=b_{m}
\end{cases}
\]
}%

אם כל המשוואות הן מעל \L{$\mathbb{R}$}, נאמר שהממ\textquotedbl ל
מעל \L{$\mathbb{R}$}. אחרת, נאמר שהממ\textquotedbl ל מעל \L{$\mathbb{C}$}.
:::

שימו לב לאינדקס הכפול: Ł$a_{ij}$ הוא המקדם של המשתנה Ł$x_{j}$ במשוואה ה-Ł$i$ )כלומר בשורה ה-Ł$i$(. Ł$b_{i}$ הוא הקבוע )איבר חופשי( במשוואה ה-Ł$i$. צריך להתרגל לכתיבה עם שני אינדקסים )ולזכור שכאן Ł$ij$ אינו מכפלה וגם לא מספר דו-ספרתי(, אבל זו הדרך הטבעית להתייחס גם למספר המשתנה וגם למספר המשוואה.

::: {.definition}
פתרון של משוואה לינארית הינו סדרת סקלרים \L{$(c_{1},c_{2},...,c_{n})$}
כך שבהצבת \L{%
\[
x_{1}=c_{1},x_{2}=c_{2},...,x_{n}=c_{n}
\]
}%

כל המשוואות בממ\textquotedbl ל מתקיימות.
:::
::: {.example}
נחזור לדוגמה קודמת:

\L{%
\[
\begin{cases}
x+y+z=3\\
x+2y+z=4\\
x+y+3z=5
\end{cases}
\]
}%

כאן המקדמים הם \L{%
\[
.a_{11}=a_{12}=a_{13}=a_{21}=a_{23}=a_{31}=a_{32}=1,\,a_{22}=2,\,a_{33}=3
\]
}%
הקבועים הם \L{$b_{1}=3,\,b_{2}=4,\,b_{3}=5$}.
:::

הרבה יותר קשה לדמיין את הגיאומטריה כאשר יש מספר משתנים גבוה מ-Ł$3$, או אפילו משוואה אחת בשני משתנים מרוכבים. אבל מבחינה אלגברית, כל המקרים האלה שייכים לקטגוריה אחת ושיטת הפתרון משותפת לכולם. באופן כללי, נשאל את השאלות הבאות על ממ`\textquotedbl `{=latex}ל:

`\beginL 1`{=latex}`\endL`{=latex}. כמה פתרונות יש?

`\beginL 2`{=latex}`\endL`{=latex}. כיצד נמצא את כל הפתרונות?

`\beginL 3`{=latex}`\endL`{=latex}. מהו מבנה קבוצת הפתרונות?

לפני כן, נראה עוד דוגמאות לממ`\textquotedbl `{=latex}ל וגם נחזור אל חלק מהדוגמאות הקודמות. קל לבדוק אם פתרון נתון הוא אכן פתרון ע`\textquotedbl `{=latex}י בדיקה שהצבתו מקיימת את כל המשוואות. עבור ממ`\textquotedbl `{=latex}ל פשוטה גם לא דרוש הרבה מאמץ כדי למצוא את קבוצת הפתרונות.

::: {.example}
א. \L{%
\[
\begin{cases}
x=1\\
y=2\\
z=3
\end{cases}
\]
}%

זו ממ\textquotedbl ל פשוטה שיש לה פתרון יחיד \L{$(x,y,z)=(1,2,3)$},
שכבר מופיע באופן מפורש.

ב. נחזור לדוגמה קודמת:\L{%
\[
\begin{cases}
x+y+z=3\\
x+2y+z=4\\
x+y+3z=5
\end{cases}
\]
}%
ניתן לבדוק ע\textquotedbl י הצבה כי \L{$(x,y,z)=(1,1,1)$} הוא פתרון
של הממ\textquotedbl ל, כי כל שלוש המשוואות מתקיימות, לעומת זאת, \L{$(x,y,z)=(2,1,0)$}
אינו פתרון כי הוא מקיים רק את שתי המשוואות הראשונות. 

האם \L{$(x,y,z)=(1,1,1)$} הוא פתרון יחיד? נראה זאת בהמשך, אבל בינתיים
נשים לב שהממ\textquotedbl ל מתארת חיתוך של שלושה מישורים במרחב. לפי
הפרק הקודם, החיתוך בין כל שניים מהמישורים שנתונים בממ\textquotedbl ל,
הוא ישר. אז החיתוך בין שלושת המישורים הוא בעצם חיתוך בין שני ישרים
)למשל: ישר החיתוך של שני המישורים הראשונים, וישר החיתוך של שני המישורים
האחרונים(. אפשר לקבוע את המצב ההדדי בין שני הישרים בעזרת ההצגות הפרמטריות
שלהם, אבל נראה שיש דרך יותר מסודרת ויעילה לחישוב קבוצת הפתרונות בדוגמה
זו ובאופן כללי.

\begin{center}
)שלושת המישורים וחיתוכיהם(
\par\end{center}

ג. \L{%
\[
\begin{cases}
x+w=1\\
y+w=2\\
z+w=3
\end{cases}
\]
}%

זו ממ\textquotedbl ל יחסית פשוטה בארבעה משתנים \L{$x,y,z,w$}. אפשר
להתייחס ל-\L{$w$} כמשתנה חופשי ואז כל שאר המשתנים תלויים בו. נשתמש
בפרמטר \L{$t$}, נציב \L{$w=t$} במשוואות ואז נחסיר \L{$t$} מכל אגף
בכל משוואה. כך נקבל\L{%
\[
\begin{cases}
x=1-t\\
y=2-t\\
z=3-t
\end{cases}
\]
}%

לכן קבוצת הפתרונות של הממ\textquotedbl ל היא \L{%
\[
\{(1-t,2-t,3-t,t)|t\in\mathbb{R}\}=\{(1,2,3,0)+t(-1,-1,-1,1)|t\in\mathbb{R}\}
\]
}%

אפשר לנסות לדמיין קבוצה זו כישר במרחב \L{$\mathbb{\mathbb{R}}^{4}$}
הארבע-מימדי. זה בהחלט לא משהו שרואים ביום-יום כי העולם המוכר הוא תלת-מימדי,
אבל זו עדיין הצגה אלגברית של ישר חד-מימדי. זה נובע מכך שיש משתנה חופשי
יחיד, ומכאן הפרמטר \L{$t$}. אם לצורך העניין היה פרמטר נוסף בהצגה
הפרמטרית )בקבוצת הפתרונות של ממ\textquotedbl ל אחרת(, הקבוצה הייתה
\textquotedbl נראית\textquotedbl{} כמו מישור ב-\L{$\mathbb{\mathbb{R}}^{4}$}
ככל שאפשר לדמיין אותו. למשל:\L{%
\[
\{(1,2,3,0)+t(-1,-1,-1,1)+s(1,1,1,1)|t\in\mathbb{R}\}
\]
}%

זו כתיבה שמזכירה הצגה פרמטרית של מישור במרחב, אלא שכאן המרחב הוא \L{$\mathbb{R}^{4}$}.
בהמשך הקורס נלמד על המושגים של מימד ותת-מרחב )כמו ישר במישור, ומישור
במרחב( באופן מדויק.

ד. עוד דוגמה קודמת:\L{%
\[
\begin{cases}
iz_{1}+z_{2}+iz_{3}+z_{4}=2i\\
z_{1}+(1+i)z_{2}+z_{2}+2iz_{3}=2
\end{cases}
\]
}%

ניתן לבדוק ע\textquotedbl י הצבה כי \L{$(z_{1},z_{2},z_{3},z_{4})=(1,0,1,0)$}
הוא פתרון של הממ\textquotedbl ל. אינטואיטיבית, אמורים להיות אינסוף
פתרונות כי מספר המשתנים גדול ממספר המשוואות. נצדיק את האינטואיציה
הזו בהמשך.

ה. ממ\textquotedbl ל של שלוש משוואות בשני משתנים מעל \L{$\mathbb{\mathbb{R}}$}:\L{%
\[
\begin{cases}
x+3y=0\\
x-y=0\\
x+y=1
\end{cases}
\]
}%

כאן מספר המשתנים גדול ממספר המשוואות, ולמעשה אין פתרון. ניתן לראות
זאת ע\textquotedbl י חיבור שתי המשוואות הראשונות, מה שנותן \L{$2x+2y=0$}
או באופן שקול \L{$x+y=0$}. זו סתירה למשוואה האחרונה. המשמעות הגיאומטרית
היא שאמנם כל שניים משלושת הישרים נחתכים, אבל נקודות החיתוך שונות ולכן
אין נקודת חיתוך משותפת לכל השלושה.
\begin{center}
)שלושת הישרים והחיתוכים ביניהם(
\par\end{center}
:::
::: {.exercise}
נסתכל על הממ\textquotedblright ל\L{%
\[
.\begin{cases}
x_{1}+x_{2}+2x_{3}-x_{4}=2\\
5x_{1}-3x_{2}-2x_{3}+x_{4}=0
\end{cases}
\]
}%

האם \L{$(x_{1},x_{2},x_{3},x_{4})=(1,1,1,2)$} הוא פתרון? האם \L{$(x_{1},x_{2},x_{3},x_{4})=(1,2,-1,-1)$}
הוא פתרון?
:::

### מטריצות

ראינו דוגמה לפעולת חיבור בין שתי משוואות. למעשה, פעולה זו משפיעה רק על המקדמים והקבועים של הממ`\textquotedbl `{=latex}ל. כאשר מחברים את שתי המשוואות הראשונות של Ł$(**)$ מקבליםŁ $$(a_{11}+a_{21})x_{1}+(a_{12}+a_{22})x_{2}+(a_{13}+a_{23})x_{3}+...+(a_{1n}+a_{2n})x_{n}=b_{1}+b_{2}$$

לצורך העניין, אפשר לשים את המשתנים בצד ולחזור אליהם בסוף. המידע של הממ`\textquotedbl `{=latex}ל אמנם קשור למשתנים, אבל הוא מגולם בסקלרים )מקדמים וקבועים(. אז זה שימושי לייצג את הממ`\textquotedbl `{=latex}ל כטבלה שבה מופיעים רק הסקלרים. טבלה כזו נקראת מטריצה.

::: {.definition}
מטריצה מסדר \L{$m\times n$} מעל \L{$\mathbb{F}$} היא טבלה
בת \L{$m$} שורות ו-\L{$n$} עמודות כך שבכל משבצת מופיע סקלר ב-\L{$\mathbb{F}$}.
בהקשר של הממ\textquotedbl ל \L{$(**)$}, נגדיר את מטריצת המקדמים
)שנקראת גם מטריצת מקדמים מצומצמת(:\L{%
\[
A=\begin{pmatrix}a_{11} & a_{12} & \cdots & a_{1n}\\
a_{21} & a_{22} & \cdots & a_{2n}\\
\vdots & \vdots & \ddots & \vdots\\
a_{m1} & a_{m2} & \cdots & a_{mn}
\end{pmatrix}
\]
}%
או \L{$A=(a_{ij})$} בצורה מקוצרת כאשר הכוונה היא שבשורה \L{$i$}
ובעמודה \L{$j$} מופיע \L{$a_{ij}$}. נגדיר גם את מטריצת המקדמים המורחבת
מסדר \L{$m\times(n+1)$} שכוללת עמודה בצד ימין )אחרי קו מפריד( בשביל
הקבועים:\L{%
\[
\left( \begin{array}{@{}cccc|c@{}}
    a_{11} & a_{12} & \cdots & a_{1n} & b_{1} \\
    a_{21} & a_{22} & \cdots & a_{2n} & b_{2} \\
    \vdots & \vdots & \ddots & \vdots & \vdots \\
    a_{m1} & a_{m2} & \cdots & a_{mn} & b_{m}
\end{array} \right)
\]
}%

נגדיר בנוסף את וקטור המשתנים \L{$X=\begin{pmatrix}x_{1}\\
x_{2}\\
\vdots\\
x_{n}
\end{pmatrix}$} וגם את וקטור הקבועים \L{$B=\begin{pmatrix}b_{1}\\
b_{2}\\
\vdots\\
b_{m}
\end{pmatrix}$}. דרך מקוצרת לכתיבת הממ\textquotedbl ל \L{$(**)$} היא המשוואה הוקטורית
\L{$AX=B$}.
:::

נראה בפרק הבא שאפשר להתייחס למטריצות כאובייקטים מתמטיים בפני עצמם ללא קשר לממ`\textquotedbl `{=latex}ל. אז גם נבין יותר לעומק את הסימון Ł$AX$ שמתאר כפל של מטריצה בוקטור עמודה באורך מתאים )בינתיים זה סימון נוח(. אמנם כתבנו וקטורי עמודה במקום וקטורי שורה )ההסבר בפרק הבא(, אבל כרגע זו רק צורת כתיבה קצת שונה.

::: {.remark}
שימו לב שאם המשתנה ה-\L{$j$} לא מופיע במשוואה ה-\L{$i$}, זה
אומר שהמקדם המתאים הוא {\beginL 0\endL} ולכן \L{$a_{ij}=0$} במטריצה.
:::
::: {.example}
א. עבור הממ\textquotedbl ל\L{%
\[
\begin{cases}
x+y+z=3\\
x+2y+z=4\\
x+y+3z=5
\end{cases}
\]
}%

מטריצת המקדמים המצומצמת היא\L{%
\[
.\begin{pmatrix}1 & 1 & 1\\
1 & 2 & 1\\
1 & 1 & 3
\end{pmatrix}
\]
}%

בשביל מטריצת המקדמים המורחבת נוסיף את עמודת הקבועים ונקבל\L{%
\[
.\left( \begin{array}{@{}ccc|c@{}}
1 & 1 & 1 & 3\\
1 & 2 & 1 & 4\\
1 & 1 & 3 & 5
\end{array} \right)
\]
}%

ב. נסתכל על הממ\textquotedbl ל\L{%
\[
.\begin{cases}
2x+y+z=1\\
x+2y+z+w=-1\\
x+y+w=2
\end{cases}
\]
}%

נשים לב שמסתתרים שני אפסים: המקדם של \L{$w$} במשוואה הראשונה, והמקדם
של \L{$z$} במשוואה השלישית. הנה כתיבה יותר מפורשת:\L{% 
\[
.\begin{cases}
    2x+y+z+0\cdot w=1\\
    x+2y+z+w=-1\\
    x+y+0\cdot z+w=2
\end{cases}
\]
}%
לכן מטריצת המקדמים המצומצמת היא\L{%
\[
.\begin{pmatrix}2 & 1 & 1 & 0\\
1 & 2 & 1 & 1\\
1 & 1 & 0 & 1
\end{pmatrix}
\]
}%

מטריצת המקדמים המורחבת היא \L{%
\[
.\left( \begin{array}{@{}cccc|c@{}}
    2 & 1 & 1 & 0 & 1\\
    1 & 2 & 1 & 1 & -1\\
    1 & 1 & 0 & 1 & 2
\end{array} \right)
\]
}%
:::
::: {.exercise}
כתבו את מטריצות המקדמים )מצומצמת ומורחבת( של הממ\textquotedbl ל\L{%
\[
.\begin{cases}
x+y+z+w=0\\
z-w=2\\
x+2y+2z+3w=8
\end{cases}
\]
}%
:::
::: {.definition}
כאשר \L{$B=\begin{pmatrix}0\\
0\\
\vdots\\
0
\end{pmatrix}$} הממ\textquotedbl ל נקראת \uline{הומוגנית} וניתן לכתוב \L{$AX=0$}.
הכוונה באגף ימין היא לוקטור האפס באורך \L{$m$} )מספר השורות של \L{$A$}(.
:::

במקרה ההומוגני ניתן להסתפק במטריצת המקדמים מצומצמת לצורך פתרון הממ`\textquotedbl `{=latex}ל. עמודת הקבועים מיותרת כי כל פעולה שנעשה תשאיר את וקטור האפס ללא שינוי )פעולות חיבור/כפל עם אפסים תמיד יחזירו אפס(.

::: {.proposition}
לכל ממ\textquotedbl ל הומוגנית קיים פתרון טריוויאלי שהוא וקטור
האפס \L{$X=0$}, כלומר הפתרון בו כל המשתנים מתאפסים.
::: 
::: {.proof}
נציב \L{$x_{1}=x_{2}=...=x_{n}=0$} בממ\textquotedbl ל ונקבל\L{%
\[
a_{i1}\cdot0+a_{i2}\cdot0+...+a_{in}=0
\]
}%

כנדרש לכל \L{$1\leq i\leq n$}.
::: 

### פעולות שורה אלמנטריות

נרצה לפשט את הממ`\textquotedbl `{=latex}ל בלי לשנות את קבוצת הפתרונות שלה. זה לא רעיון חדש: כבר במקרה של שתי משוואות בשני משתנים ראינו שאפשר לחבר/לחסר בין המשוואות וגם להשתמש בכפל בסקלר. כל פעולה כזו לא משנה את קבוצת הפתרונות, כי מדובר בפעולה הפיכה )אפשר לשחזר את הממ`\textquotedbl `{=latex}ל המקורית מתוך צורתה החדשה(. במילים אחרות, פעולות כאלו יוצרות ממ`\textquotedbl `{=latex}ל שקולה לממ`\textquotedbl `{=latex}ל המקורית, ויש בזה טעם אם היא יותר פשוטה.

::: {.definition}
תהי \L{$A=(a_{ij})$} מטריצה מסדר \L{$m\times n$} מעל \L{$\mathbb{F}$}.
נסמן ב-\L{$R_{1},R_{2},...,R_{m}$} את שורות המטריצה \L{$A$}, כלומר
\L{$R_{i}=(a_{i1},a_{i2},...,a_{in})$} לכל \L{$1\leq i\leq m$}.
להלן שלושה סוגי פעולות על שורות \L{$A$} הנקראות \uline{פעולות שורה
אלמנטריות:}

{\beginL 1\endL}. כפל השורה \L{$R_{i}$} בסקלר \L{$c\in F$} שאינו
\L{$0$}. נסמן פעולה זו כך: \L{$cR_{i}\rightarrow R_{i}$}.

{\beginL 2\endL}. הוספה לשורה \L{$R_{i}$} את הכפולה של השורה \L{$R_{j}$}
בסקלר \L{$c\in F$} כאשר \L{$i\neq j$}. נסמן \L{$R_{i}+cR_{j}\rightarrow R_{i}$}.
השורה \L{$R_{j}$} נשארת ללא שינוי.

{\beginL 3\endL}. החלפת השורות \L{$R_{i}$} ו-\L{$R_{j}$} עבור \L{$i\neq j$}.
נסמן \L{$R_{i}\leftrightarrow R_{j}$}.
:::
::: {.example}
נדגים כל סוג פעולה על המטריצה \L{%
\[
.\begin{pmatrix}1 & 2 & 3\\
4 & 5 & 6\\
7 & 8 & 9
\end{pmatrix}
\]
}%

{\beginL 1\endL}. נכפיל את השורה הראשונה ב-\L{$2$}:\L{%
\[
\begin{pmatrix}1 & 2 & 3\\
4 & 5 & 6\\
7 & 8 & 9
\end{pmatrix}\overset{2R_1 \to R_1}{\underset{R_1\leftarrow \dfrac{1}{2}R_1}{\longleftrightarrow}}\begin{pmatrix}2 & 4 & 6\\
4 & 5 & 6\\
7 & 8 & 9
\end{pmatrix}
\]
}%

את הפעולה משמאל לימין ציינו מעל לחץ, ומתחתיו ציינו את הפעולה ההפוכה
מימין לשמאל. פעולה זו היא כפל השורה הראשונה ב-\L{$\frac{1}{2}$}.

{\beginL 2\endL}. נוסיף לשורה השלישית כפולה של השורה הראשונה בסקלר
\L{$-3$}:\L{%
\[
\begin{pmatrix}1 & 2 & 3\\
4 & 5 & 6\\
7 & 8 & 9
\end{pmatrix}\overset{R_3-3R_1 \to R_3}{\underset{R_3\leftarrow R_3+3R_1}{\longleftrightarrow}}\begin{pmatrix}1 & 2 & 3\\
4 & 5 & 6\\
4 & 2 & 0
\end{pmatrix}
\]
}%

שימו לב שהשורה הראשונה לא משתנה. החישוב שעשינו עבור השורה השלישית
הוא \L{$(7,8,9)-3(1,2,3)=(4,2,0)$}. הפעולה ההפוכה היא הוספה לשורה
השלישית כפולה של השורה הראשונה בסקלר \L{$3$}, כלומר הסקלר הנגדי לסקלר
המקורי )שינוי סימן(.

{\beginL 3\endL}. נחליף בין השורה השנייה לשורה השלישית:\L{%
\[
\begin{pmatrix}1 & 2 & 3\\
4 & 5 & 6\\
7 & 8 & 9
\end{pmatrix}\overset{R_2 \leftrightarrow R_3}{\underset{R_3 \leftrightarrow R_2}{\longleftrightarrow}}\begin{pmatrix}1 & 2 & 3\\
7 & 8 & 9\\
4 & 5 & 6
\end{pmatrix}
\]
}%

כאן הפעולה ההפוכה היא אותה הפעולה: החלפה בין השורה השנייה לשורה השלישית.
:::
::: {.remark}
באופן כללי, כל פעולות השורה האלמנטריות הן הפיכות. נבהיר למה
הכוונה בכל מקרה:

{\beginL 1\endL}. לכל \L{$c\neq0$} ולכל \L{$1\leq i\leq m$} הפעולה
ההפוכה ל-\L{$cR_{i}\rightarrow R_{i}$} היא \L{$\frac{1}{c}R_{i}\rightarrow R_{i}$}.

{\beginL 2\endL}. לכל \L{$c\in F$} ולכל \L{$i\neq j$} הפעולה ההפוכה
ל-\L{$R_{i}+cR_{j}\rightarrow R_{i}$} היא \L{$R_{i}-cR_{j}\rightarrow R_{i}$}.
אכן, אם מבצעים את הפעולה הראשונה ואחריה את השנייה )או בסדר הפוך(,
התוצאה היא \L{$R_{i}+cR_{j}-cR_{j}\rightarrow R_{i}$} או בקיצור \L{$R_{i}\to R_{i}$}.
החזרה למקור היא המשמעות של פעולה הפוכה.

{\beginL 3\endL}. לכל \L{$i\neq j$} הפעולה ההפוכה להחלפה \L{$R_{i}\leftrightarrow R_{j}$}
היא אותה ההחלפה \L{$R_{i}\leftrightarrow R_{j}$}.
:::
::: {.proposition}
לכל ממ\textquotedbl ל שהיא, קבוצת הפתרונות שלה לא משתנה לאחר
ביצוע מספר סופי )גדול ככל שיהיה( של פעולות שורה אלמנטריות.
::: 

במילים אחרות, כל Ł$n$-יה Ł$(c_{1},c_{2},...,c_{n})$ היא פתרון של הממ`\textquotedbl `{=latex}ל החדשה )שמתקבלת אחרי כל הפעולות( אם ורק אם היא פתרון של הממ`\textquotedbl `{=latex}ל המקורית.

::: {.proof}
לכל ממ\textquotedbl ל ולכל פעולת שורה אלמנטרית, כל פתרון של
הממ\textquotedbl ל לפני הפעולה נשאר פתרון של הממ\textquotedbl ל
שמתקבלת בעקבות הפעולה. ולהיפך, ההפיכות של הפעולה מראה שכל פתרון של
הממ\textquotedbl ל החדשה הוא גם פתרון של הממ\textquotedbl ל הקודמת
לה. אז קבוצת הפתרונות נשארת ללא שינוי.

אם נמשיך כך ונבצע מספר סופי של פעולות שורה אלמנטריות, קבוצת הפתרונות
תישמר בכל שלב ולכן גם בסוף התהליך היא תישאר זהה לקבוצת הפתרונות המקורית.
::: 
::: {.remark}
כפל שורה ב-\L{$0$} אינה פעולה הפיכה. למעשה, הוא מוחק את המשוואה
המתאימה בממ\textquotedbl ל כי \L{$0=0$} מתקיים ללא קשר למשתנים.
זה בדרך כלל ישפיע על קבוצת הפתרונות )יגדיל אותה( ולכן יש להימנע מכפל
שורה ב-\L{$0$}. הנה דוגמה פשוטה במקרה של שתי משוואות בשני משתנים:\L{%
\[
\begin{cases}
x=1\\
y=0
\end{cases}
\]
}%

לממ\textquotedbl ל יש פתרון יחיד \L{$(x,y)=(1,0)$} ושני המשתנים
תלויים. נכפיל את השורה השנייה ב-\L{$0$} במטריצת המקדמים המורחבת:
\L{%
\[
\left( \begin{array}{@{}cc|c@{}}
1 & 0 & 1\\
0 & 1 & 0
\end{array}\right) \xrightarrow{0\cdot R_2\to R_2}
    \left( \begin{array}{@{}cc|c@{}}
    1 & 0 & 1\\
    0 & 0 & 0
\end{array} \right)
\]
}%

הממ\textquotedbl ל החדשה היא\L{%
\[
.\begin{cases}
x=1\\
0=0
\end{cases}
\]
}%

עכשיו \L{$y$} משתנה חופשי. נציב \L{$y=t$} ונקבל קבוצת פתרונות \L{$\{(1,t)|t\in\mathbb{R}\}$},
כלומר התווספו אינסוף פתרונות. הממ\textquotedbl ל החדשה לא שקולה לממ\textquotedbl ל
המקורית כי הכפלנו ב-\L{$0$} ובכך מחקנו משוואה.
:::
::: {.example}
נסתכל על ממ\textquotedbl ל הומוגנית:\L{%
\[
\begin{cases}
x+y+z=0\\
2x+2z=0\\
3x+5y+7z=0
\end{cases}
\]
}%

נבצע סדרה של פעולות על מטריצת המקדמים המצומצמת:

\L{%
    \begin{alignat*}{3}
        &\begin{pmatrix} 1 & 1 & 1 \\ 2 & 0 & 2 \\ 3 & 5 & 7 \end{pmatrix}
        &&\xrightarrow{\dfrac{1}{2}R_2 \to R_2}
        \begin{pmatrix} 1 & 1 & 1 \\ 1 & 0 & 1 \\ 3 & 5 & 7 \end{pmatrix}
        &&\xrightarrow{R_1 - R_2 \to R_1}
        \begin{pmatrix} 0 & 1 & 0 \\ 1 & 0 & 1 \\ 3 & 5 & 7 \end{pmatrix} \\
        \xrightarrow{R_1 \leftrightarrow R_2}&\begin{pmatrix} 1 & 0 & 1 \\ 0 & 1 & 0 \\ 3 & 5 & 7 \end{pmatrix}
        &&\xrightarrow{R_3 - 3R_1 \to R_3}
        \begin{pmatrix} 1 & 0 & 1 \\ 0 & 1 & 0 \\ 0 & 5 & 4 \end{pmatrix}
        &&\xrightarrow{R_3 - 5R_2 \to R_3}
        \begin{pmatrix} 1 & 0 & 1 \\ 0 & 1 & 0 \\ 0 & 0 & 4 \end{pmatrix} \\
        \xrightarrow{\dfrac{1}{4}R_3 \to R_3}&\begin{pmatrix} 1 & 0 & 1 \\ 0 & 1 & 0 \\ 0 & 0 & 1 \end{pmatrix}
        &&\xrightarrow{R_1 - R_3 \to R_1}
        \begin{pmatrix} 1 & 0 & 0 \\ 0 & 1 & 0 \\ 0 & 0 & 1 \end{pmatrix}
        &&
    \end{alignat*}
}%

נסביר בהמשך איך בחרנו את הפעולות האלו. בינתיים נציין שסדרה כזו של
פעולות נקראת \uline{דירוג מטריצה}, וכאן היא מראה כי הממ\textquotedbl ל
המקורית שקולה לממ\textquotedbl ל הפשוטה שמתאימה למטריצה האחרונה שקיבלנו:\L{%
\[
\begin{cases}
x=0\\
y=0\\
z=0
\end{cases}
\]
}%

לכן גם לממ\textquotedbl ל המקורית יש פתרון יחיד, שהוא הפתרון הטריוויאלי.
שימו לב לצורתה של המטריצה האחרונה שהתקבלה בתהליך הדירוג. זו צורה נוחה
מאוד בגלל ריבוי האפסים, ובנוסף כל שאר האיברים הם \L{$1$}. לכן, בכל
משוואה בממ\textquotedbl ל האחרונה יש משתנה תלוי שהוא כבר מבודד )ובמקרה
זה אין אף משתנה חופשי(.
:::

באופן כללי, צריך להתייחס לשתי שאלות כאשר מנסים לפשט ממ`\textquotedbl `{=latex}ל:

`\beginL 1`{=latex}`\endL`{=latex}. איזו פעולת שורה אלמנטרית בוחרים בכל שלב?

`\beginL 2`{=latex}`\endL`{=latex}. מתי עוצרים את הדירוג? כלומר, מתי המטריצה פשוטה מספיק כדי לפתור את הממ`\textquotedbl `{=latex}ל?

### מטריצות מדורגות ומדורגות קנונית

בדוגמה הקודמת שלוש המטריצות האחרונות שקיבלנו עונות על תנאי ההגדרה הבאה:

::: {.definition}
מטריצה נקראת \uline{מדורגת} אם:

{\beginL 1\endL}. אם במטריצה יש שורות אפסים, אז הן מופיעות מתחת לכל
שאר השורות.

{\beginL 2\endL}. בכל שורה שאינה שורת אפסים, האיבר הראשון )משמאל(
שאינו \L{$0$} נקרא \uline{האיבר המוביל} של שורה זו, והוא מופיע משמאל
לאיבר המוביל של השורה מתחתיו.
:::
::: {.example}
א. במטריצה \L{%
\[
\begin{pmatrix}1 & 0 & 1\\
0 & 1 & 0\\
0 & 0 & 4
\end{pmatrix}
\]
}%

האיברים המובילים הם \L{$1,1,4$} לפי סדר השורות והם מופיעים בסדר הנכון
)זזים ימינה כאשר יורדים שורה(. בנוסף, אין בכלל שורות אפסים ולכן זו
מטריצה מדורגת.

ב. המטריצה\L{%
\[
\begin{pmatrix}1 & 0 & 1\\
0 & 1 & 0\\
0 & 5 & 4
\end{pmatrix}
\]
}%

אינה מדורגת כי האיבר המוביל של השורה השלישית )\L{$5$}( מופיע באותה
העמודה של האיבר המוביל של השורה השנייה )\L{$1$}(. 

ג. המטריצה \L{%
\[
\begin{pmatrix}1 & 2 & 3\\
0 & 0 & 4\\
0 & 0 & 0
\end{pmatrix}
\]
}%

מדורגת. שורה האפסים מופיעה בסוף, והאיבר המוביל של השורה הראשונה )\L{$1$}(
מופיע משמאל לזה של השורה השנייה )\L{$4$}(.

ד. המטריצה \L{%
\[
\begin{pmatrix}1 & 0 & 0\\
0 & 0 & 0\\
0 & 0 & 1
\end{pmatrix}
\]
}%

אינה מדורגת כי יש שורת אפסים מעל לשורה שאינה כולה אפסים.
:::

מטריצות מדורגות הן יחסית נוחות, אך יש מטריצות מדורגות מסוג יותר מסוים שהוא עוד יותר נוח בפתרון ממ`\textquotedbl `{=latex}ל.

::: {.definition}
מטריצה נקראת \uline{מדורגת קנונית} אם:

{\beginL 1\endL}. היא מדורגת, כלומר מקיימת את שני תנאי ההגדרה הקודמת.

{\beginL 2\endL}. האיבר המוביל בכל שורה )אם הוא קיים( הוא \L{$1$}.
אפשר גם לקרוא לו אחד מוביל.

{\beginL 3\endL}. בכל עמודה של אחד מוביל, כל שאר האיברים הם \L{$0$}.
:::
::: {.example}
א. ראינו כבר את המטריצה\L{%
\[
,\begin{pmatrix}1 & 0 & 0\\
0 & 1 & 0\\
0 & 0 & 1
\end{pmatrix}
\]
}%

שנקראת מטריצת היחידה מסדר \L{$3\times3$}. היא מדורגת קנונית כי אין
בה שורת אפסים, כל האיברים המובילים הם \L{$1$} ומופיעים בסדר הנכון, וכל
שאר האיברים הם \L{$0$}.

ב. המטריצה \L{%
\[
\begin{pmatrix}1 & 0 & 1\\
0 & 1 & 0\\
0 & 0 & 4
\end{pmatrix}
\]
}%

מדורגת אך לא מדורגת קנונית, כי האיבר המוביל התחתון אינו \L{$1$}.
בנוסף, לא כל האיברים מעליו הם \L{$0$}.

ג. המטריצה \L{%
\[
\begin{pmatrix}1 & 0 & 0 & 2\\
0 & 0 & 1 & 3\\
0 & 0 & 0 & 0
\end{pmatrix}
\]
}%

מדורגת קנונית כי שני האיברים המובילים הם \L{$1$} ומופיעים בסדר הנכון.
חוץ מהם יש רק אפסים בעמודות שלהם, וגם שורת האפסים מופיעה בסוף.
:::

מהי הצורה הכללית של מטריצה מדורגת קנונית מסדר Ł$m\times n$?

::: center
)מטריצה מדורגת קנונית עם דגש על האיברים המובילים(
:::

האיברים המובילים מופיעים בעמודות Ł$k_{1},k_{2},....,k_{r}$. Ł$r$ הוא גם מספר השורות שאינן כולן אפסים )בכל שורה כזו יש איבר מוביל אחד(.

::: {.definition}
נניח שקיבלנו צורה מדורגת קנונית של מטריצת מקדמים מצומצמת \L{$A$}
של ממ\textquotedbl ל \L{$AX=B$}.

א. כל משתנה שמתאים לעמודה בה מופיע איבר מוביל נקרא משתנה תלוי. שאר
המשתנים נקראים חופשיים.

ב. למספר המשתנים התלויים נקרא הדרגה של הממ\textquotedbl ל/מטריצה.
נסמן \L{$\text{rank}(A)$}.
:::
::: {.remark}
כל מטריצה ניתנת לדירוג שבסופו מתקבלת מטריצה מדורגת קנונית. מטריצה
זו היא יחידה וניתן להשתמש בה כדי לקבוע את הדרגה של המטריצה המקורית,
וגם את קבוצת הפתרונות שלה.
:::

הרעיון של משתנה תלוי זה שיש משוואה שמתארת את התלות שלו במשתנים החופשיים )או חלקם אם בכלל(. ניתן להציב סקלרים שרירותיים במשתנים החופשיים בכל משוואה, ולקבל את הערכים המתאימים של המשתנים התלויים.

::: {.example}
נפתור את הממ\textquotedbl ל\L{%
\[
.\begin{cases}
x_{1}+ix_{4}=1+i\\
x_{3}+x_{4}=2
\end{cases}
\]
}%

מטריצת המקדמים המורחבת היא\L{%
\[
\left( \begin{array}{@{}cccc|c@{}}
    1 & 0 & 0 & i & 1+i\\
    0 & 0 & 1 & 1 & 2
\end{array} \right)
\]
}%

היא כבר מדורגת קנונית ויש בה שני אחדות מובילים. לכן הדרגה היא \L{$2$}
והמשתנים התלויים הם \L{$x_{1},x_{3}$}. נציב \L{$(x_{2},x_{4})=(s,t)\in\mathbb{C}^{2}$}
בשתי המשוואות ונבודד את המשתנים התלויים: \L{%
\[
.\begin{cases}
x_{1}=1+i-it\\
x_{3}=2-t
\end{cases}
\]
}%

לכן, קבוצת הפתרונות נתונה ע\textquotedbl י\L{%
\[
.\{(1+i-it,s,2-t,t)|s,t\in\mathbb{C}\}
\]
}%

יש שני פרמטרים בהצגה הפרמטרית כי יש שני משתנים חופשיים.
:::

### שיטת הדירוג של גאוס

כיצד נבחר אילו פעולות השורה האלמנטריות לבצע בכל שלב כדי להעביר מטריצה נתונה Ł$A=(a_{ij})$ לצורה מדורגת קנונית? יש שיטה מסודרת )אלגוריתם( שנקראת שיטת הדירוג של גאוס. בהינתן מטריצה, נפעל לפי השלבים הבאים:

`\beginL 1`{=latex}`\endL`{=latex}. נחפש בעמודה הראשונה איבר Ł$a_{i1}\neq0$ ונהפוך אותו ל-Ł$1$ ע`\textquotedbl `{=latex}י הפעולה Ł$\frac{1}{a_{i1}}R_{i}\to R_{i}$ )אם יש רק אפסים, אפשר לדלג לשלב `\beginL 3`{=latex}`\endL`{=latex}(. אם Ł$i\neq1$, נבצע גם את ההחלפה Ł$R_{i}\leftrightarrow R_{1}$ כדי שיופיע Ł$1$ בפינה השמאלית העליונה.

`\beginL 2`{=latex}`\endL`{=latex}. נשתמש ב-Ł$1$ שקיבלנו בשורה הראשונה כדי לאפס את כל האיברים מתחתיו. כלומר: אם מופיע Ł$a_{j1}$ בשורה ה-Ł$j$, נבצע את הפעולה Ł$R_{j}-a_{j1}R_{1}\to R_{j}$ לכל Ł$j>1$ כך ש-Ł$a_{j1}\neq0$. כך נקבל עמודה שכמעט כולה אפסים חוץ מהאחד המוביל בשורה הראשונה.

`\beginL 3`{=latex}`\endL`{=latex}. ממשיכים באופן דומה עם העמודה השנייה וחוזרים על אותם השלבים כדי לאפס את כל האיברים חוץ מאיבר אחד שיופיע בשורה השנייה כ-Ł$1$ )אם מלכתחילה יש רק אפסים מתחת לשורה הראשונה, ממשיכים הלאה לעמודה הבאה(. יש להימנע מפעולה שתשנה את העמודה הראשונה.

`\beginL 4`{=latex}`\endL`{=latex}. ממשיכים באופן דומה עם שאר העמודות לפי הסדר, בלי לשנות את העמודות הקודמות.

`\beginL 5`{=latex}`\endL`{=latex}. עוצרים אחרי שעברנו על כל העמודות, או כאשר כל השורות מתחת לאחד המוביל האחרון הן שורות אפסים )ואז אין מה לעשות איתן(.

::: {.example}
נחזור לדוגמה קודמת, אבל הפעם נעבוד קצת שונה וגם נסביר את בחירת הפעולות. ניתן לבצע מספר פעולות במקביל אם הן בלתי תלויות, כמו להחסיר כפולות של שורה כלשהי משורות אחרות )לכל שורה כפולה משלה(. 
\L{%
\begin{equation*}
    \begin{aligned}
        \begin{pmatrix}1 & 1 & 1 \\ 2 & 0 & 2 \\ 3 & 5 & 7 \end{pmatrix}
        &\xrightarrow[R_2-2R_1 \to R_2]{R_3-3R_1 \to R_3}
        \begin{pmatrix}1 & 1 & 1 \\ 0 & -2 & 0 \\ 0 & 2 & 4\end{pmatrix}
        &\xrightarrow{-\dfrac{1}{2}R_2 \to R_2}
        \begin{pmatrix}1 & 1 & 1 \\ 0 & 1 & 0 \\ 0 & 2 & 4 \end{pmatrix} \\
        &\xrightarrow[R_1-R_2 \to R_1]{R_3-2R_2 \to R_3}
        \begin{pmatrix}1 & 0 & 1 \\ 0 & 1 & 0 \\ 0 & 0 & 4\end{pmatrix}
        &\xrightarrow{\dfrac{1}{4}R_3 \to R_3}
        \begin{pmatrix}1 & 0 & 1 \\ 0 & 1 & 0 \\ 0 & 0 & 1\end{pmatrix}
        &\xrightarrow{R_1-R_3 \to R_1}
        \begin{pmatrix}1 & 0 & 0 \\ 0 & 1 & 0 \\ 0 & 0 & 1\end{pmatrix}
    \end{aligned}
\end{equation*}
}%

בשלב הראשון כבר היה \L{$1$} בשורה הראשונה. השתמשנו בו כדי לאפס את
האיברים מתחתיו. 

בשלב השני הפכנו את \L{$-2$} ל-\L{$1$}. בשלב השלישי איפסנו את שאר
האיברים בעמודה השנייה.

בשלב הרביעי הפכנו את \L{$4$} ל-{\beginL 1\endL}. בשלב החמישי איפסנו
את שאר האיברים בעמודה השלישית.

התוצאה היא מטריצה מדורגת קנונית )למעשה מטריצת היחידה( עם אחדות מובילים ואפסים בלבד.
:::
::: {.remark}
לרוב יש יותר מדרך אחת לפעול לפי שיטת הדירוג של גאוס, וזה גם לגיטימי לעשות פעולה מיותרת כל עוד היא חוקית. כל דרך
היא נכונה ובלבד שאין בה כפל שורה ב-\L{$0$} )או טעות חישוב(. בכל מקרה הצורה המדורגת קנונית
היא יחידה ולכן אינה תלויה בדרך הדירוג.
:::

`\selectlanguage{american}`{=latex}