
# פרק 0: קבוצות ומספרים {.unnumbered}

## 0.1 קבוצת המספרים הטבעיים והגדרת קבוצה

המתמטיקה מתחילה בחשבון, וחשבון מבוסס על ספירה. המספר $1$ מתאר את היחידה הבסיסית, לצורך העניין אצבע אחת (שבעזרתה אפשר לספור כל מיני דברים(. ניתן להוסיף $1$ לספירה כאוות נפשנו, ואם נמשיך כך לנצח (בדמיון שלנו לפחות( נייצר אינסוף מספרים שלא בהכרח נדע איך לקרוא להם כי השמות יהיו ארוכים מאוד. אבל יש שם לקבוצה של כל המספרים האלה: מספרים טבעיים. הסימון המקובל הוא $\mathbb{N}$, ואפשר למנות את איברי הקבוצה באופן הבא  $$\mathbb{N}=\{1,1+1,1+1+1,...\}=\{1,2,3,...\}$$

הסוגריים המסולסלים מתארים קבוצה שאיבריה מופיעים בין הסוגריים ומופרדים עי פסיקים. מאחר שהקבוצה אינסופית, אנחנו נאלצים לכתוב \... מתוך הנחה שברור איך להמשיך.

::: {.remark}
לפעמים גם $0$ נחשב מספר טבעי, אבל לא בקורס שלנו וזה לא באמת חשוב. מבחינה היסטורית ופילוסופית, $0$ הוא מספר מוזר ומיוחד כי לא רואים אותו בטבע. הוא מתאר את מה שאינו.
:::

::: hdef
קבוצה היא אוסף כלשהו של איברים (לא בהכרח מספרים(לא חשיבות לסדר הופעתם.
:::

זו הגדרה מאוד כללית, ובלבד שיהיה ברור מהגדרת הקבוצה אילו איברים שייכים לה ואילו לא. אם הקבוצה היא $A$, אז נכתוב $a\in A$ כדי לומר שהאיבר $a$ שייך לקבוצה $A$. אם הוא לא שייך לה, נכתוב $a\notin A$.

::: center
(עיגול עם נקודה בתוכו שמסומנת כשייכת, ונקודה בחוץ שמסומנת כלא שייכת(
:::

::: example
משפחת לוי כוללת את דרור (האב(, אורית (האם( ואיתי (הבן(. נקרא לקבוצת אנשים זו $L$ ונתאר אותה באופן מפורש תוך שימוש בלועזית (אפשר גם בעברית(  $$L=\{\text{{Dror, Itay, Orit}}\}$$

בפרט, מתקיים $\text{{Itay}\ensuremath{\in}L}$ אך $\text{{Ofer}\ensuremath{\notin}L}$ כי מבין השניים האלה רק איתי שייך למשפחה. נדגיש שאין חשיבות לסדר האיברים בתוך הקבוצה, ובדרך כלל יש יותר מדרך אחת להציג את הקבוצה. למשל, כאן גם מתקיים  $$L=\{\text{{Itay, Dror, Orit}}\}=\{\text{{Orit, Itay, Dror}}\}$$
:::

::: self
האם מתקיים $100^{100}\in\mathbb{N}$? $100^{-100}\in\mathbb{N}$? $(-100)^{100}\in\mathbb{N}$?
:::

ניתן להגדיר תת-קבוצות של $\mathbb{N}$ עי שימוש בתכונות. למשל, את קבוצת המספרים הזוגיים החיוביים $2\mathbb{N}$ ניתן להגדיר באופן הבא:  $$2\mathbb{N}=\{n\in\mathbb{N}|n\text{ {is divided by} 2}\}=\{2,4,6,...\}$$

הסימן $\in$ מתאר שייכות, ולכן הנוסחה $n\in\mathbb{N}$ פירושה המספר $n$ שייך לקבוצה $\mathbb{N}$. הקו $|$ שמפריד בין הנוסחה לתנאי, פירושו כך ש-. לכן, הגדרת הקבוצה אומרת לנו שמדובר בקבוצת כל המספרים מהצורה $n\in\mathbb{N}$ כך ש-$n$ מתחלק ב-$2$. אפשר גם להגדיר את הקבוצה הזו עי נוסחה מפורשת $2n$ שתפיק את כל המספרים הזוגיים החיוביים כאשר נציב בה כל מספר מהצורה $n\in\mathbb{N}$. הפעם הכתיבה היא כדלקמן  $$2\mathbb{N}=\{2n|n\in\mathbb{N}\}$$

שימו לב ששתי צורות הכתיבה דומות (נוסחה בצד שמאל ותנאי בצד ימין, עם קו מפריד באמצע(. ההבדל הוא שבצורה הראשונה הנוסחה מתייחסת לקבוצה ידועה ($\mathbb{N}$( והתנאי דרוש כדי לקבוע את השייכות לקבוצה החדשה. בצורה השנייה יש נוסחה של משתנה $n$, והתנאי מתייחס לערכי המשתנה שיש להציב בנוסחה (כאן התנאי הוא זה שמתייחס ל-$\mathbb{N}$(. בהמשך הפרק נוכיח שאכן שתי ההגדרות של קבוצת הזוגיים הן הגדרות שקולות, כלומר שתיהן אכן מתארות את המספרים $2,4,6,...$ ושום מספר אחר. זה אולי כבר נראה ברור, אבל נשאלת השאלה איך כותבים הוכחה מסודרת.

## 0.2 קבוצות מספרים נוספות

ב-$\mathbb{N}$ יש פעולות חיבור וכפל. הפעולות ההפוכות, חיסור וחילוק, דורשות הרחבה של $\mathbb{N}$ לקבוצות יותר גדולות. למשל, למשוואה $x+2=1$ אין פתרון טבעי ואנחנו יודעים שאפשר לפתור אותה עי חיסור $2$ מכל אגף ואז הפתרון יהיה $x=-1$, שהוא מספר שלילי. בעצם, מגדירים את $-1$ כפתרון של המשוואה $x+1=0$ וזה מוביל להגדרה של המספרים השלמים  $$\mathbb{Z}=\{...,-3,-2,-1,0,1,2,3,...\}=\{n-m|n,m\in\mathbb{\mathbb{N}}\}$$

שימו לב לכתיבה בצד ימין. זו דרך להגדיר את קבוצת השלמים בעזרת קבוצת הטבעיים, כאשר הכוונה היא לקבוצת כל המספרים מהצורה $n-m$ כאשר $n,m$ הם מספרים טבעיים (פה יש שני משתנים(. יש יותר מדרך אחת לכתוב מספר שלם כהפרש של מספרים טבעיים (למעשה אינסוף(.

ניתן גם להרחיב את $\mathbb{Z}$ כך שיהיה ניתן לבצע חילוק. בתור התחלה מגדירים לכל $m\neq0$ שלם את המספר ההופכי $\frac{1}{m}$, וכדי לאפשר כפל גם מוסיפים את כל השברים מהצורה $\frac{n}{m}$ כאשר $n\in\mathbb{Z}$. כך מקבלים את קבוצת המספרים הרציונליים  $$\mathbb{Q}=\{\frac{n}{m}|m,n\in\mathbb{\mathbb{Z}},\,m\neq0\}$$

גם כאן יש אינסוף דרכים להציג מספר רציונלי כמנה של מספרים שלמים, ואין עם זה בעיה מבחינת הגדרת הקבוצה. אנחנו רגילים להצגה הפשוטה ביותר, לאחר צמצום המחלקים המשותפים של המונה והמכנה.

זה מביא אותנו לקבוצת המספרים הממשיים $\mathbb{R}$, שהיא הקבוצה העיקרית שנתמקד בה בקורס. קבוצה זו מכילה את קבוצת המספרים הרציונליים (כל מספר רציונלי הוא ממשי(, אבל יש בה מספרים נוספים שנקראים אי-רציונליים. יש הרבה מה לומר על מספרים ממשיים, אבל הדיון המלא מתאים לקורס בחשבון דיפרנציאלי ואינטגרלי. אז נסתפק באפיון הבא: ניתן להציג כל $x\in\mathbb{R}$ בהצגה עשרונית מהצורה  $$x=\pm d_{n}...d_{2}d_{1}d_{0}.d_{-1}d_{-2}d_{-3}...$$ כאשר $d_{n},d_{n-1},...,d_{0},d_{-1},d_{-2},...$ הן ספרות עשרוניות בין $0$ ל-$9$ (כולל(, והנקודה העשרונית מפרידה בין החלק השלם משמאל לחלק השברי מימין. $x$ הוא רציונלי כאשר סדרת הספרות העשרוניות היא מחזורית החל משלב מסוים. למשל

 $$\begin{aligned}
\frac{1}{5}=0.200000000000...\\
\frac{1}{6}=0.166666666666...\\
\frac{1}{7}=0.142857142857...
\end{aligned}$$

במקרה הראשון הספרה $0$ חוזרת על עצמה (אפשר להשמיט אותה ולקבל הצגה סופית(, במקרה השני הספרה $6$ חוזרת על עצמה, ובמקרה השלישי הרצף $142857$ חוזר על עצמו. המחזוריות נובעת מאופן החישוב של הספרות העשרוניות (לפי חילוק ארוך(.

המספר הוא אי-רציונלי כאשר אין מחזוריות באף שלב של ההצגה העשרונית, ואז החוקיות של סדרת הספרות העשרוניות עלולה להיות מסובכת מאוד. למשל  $$\begin{aligned}
\sqrt{2}=1.41421356237309504880168872420969807856967187537...\\
\pi=3.14159265358979323846264338327950288419716939937...
\end{aligned}$$ נדגיש שאלה מספרים אי-רציונליים מיוחדים כי יש להם משמעות גיאומטרית. $\sqrt{2}$ הוא אורך היתר של משולש ישר-זווית עם שני ניצבים באורך $1$, לפי משפט פיתגורס. $\pi$ הוא היקף מעגל שקוטרו באורך $1$.

מבחינת הקורס, המספרים האי-רציונליים הרלוונטיים הם בעיקר שורשים כמו $\sqrt{2}$ שהם יחסית נוחים לחישובים. אבל טוב לזכור שיש המון מספרים אי-רציונליים (יותר מאשר מספרים רציונליים במובן מסוים(, והם משלימים את המספרים הרציונליים למה שנקרא הישר הממשי. ניתן לחשוב על המספרים כנקודות על ישר עם ראשית $0$. המספרים החיוביים מופיעים בצד ימין, ואילו המספרים השליליים מופיעים בצד שמאל.

::: center
(הישר הממשי(
:::

נשארה עוד קבוצה אחת, שהיא הגדולה ביותר מבין קבוצות המספרים שנעסוק בהן. באופן דומה להגדרת $-1$ כשורש (פתרון( של המשוואה $x+1=0$, אפשר להגדיר את $i$ כשורש של המשוואה $x^{2}+1=0$. זהו מספר מדומה, שהרי אין פתרון ממשי למשוואה זו (ערך המינימום של הפונקציה הוא $1$(. המספר $i$ לא ניתן למדידה במציאות אך הוא שימושי מאוד במתמטיקה, פיזיקה וחלק מההנדסות. לפי ההגדרה מתקיים $i^{2}=-1$ וזה מספיק כדי להגדיר את קבוצת המספרים המרוכבים ואת פעולות החשבון המתאימות לה.

 $$\mathbb{\mathbb{C}}=\{a+bi|a,b\in\mathbb{R}\}$$

ההצגה $a+bi$ עבור $a,b\in\mathbb{R}$ הינה יחידה. כלומר, אם מתקיים $a+bi=c+di$ עבור $c,d\in\mathbb{R}$, אז בהכרח $a=c,\,b=d$.

::: hdef
עבור $z=x+yi$ מרוכב עם $x,y\in\mathbb{R}$ נגדיר את החלק הממשי $\text{{Re}}(z)=x$ ואת החלק המדומה $\text{{Im}}(z)=y$. בנוסף, נגדיר את המספר הצמוד $\overline{z}=x-yi$.
:::

שימו לב כי בניגוד לשמו, החלק המדומה הוא מספר ממשי )זהו המקדם של $i$, שהוא עצמו באמת מדומה(. מספר מרוכב נקרא מדומה אם החלק הממשי שלו הוא $0$, כלומר זה מספר מהצורה $yi$ כאשר $y\in\mathbb{R}$.

::: examples
א. $\text{{Re}}(3+5i)=3,\:\text{{Im}}(3+5i)=5,\:\overline{3+5i}=3-5i$

ב. $\text{{Re}}(4i)=0,\:\text{{Im}}(4i)=4,\:\overline{4i}=-4i$

ג. $\text{{Re}}(3)=3,\:\text{{Im}}(3)=0,\:\overline{3}=3$ כאשר זיהינו את $3$ כמספר מרוכב עם חלק מדומה $0$ לפי ההצגה $3=3+0\cdot i$.
:::

::: self
לכל $z\in\mathbb{C}$ הראו כי המספר הצמוד ל-$\overline{z}$ הוא $z$.
:::

בפרק הבא נדון בפעולות, תכונות וחלק מהשימושים של המספרים המרוכבים. את סוף הפרק הזה נקדיש לקשר בין כל קבוצות המספרים.

## 0.3 תורת הקבוצות על קצה המזלג

ראינו את יחס השייכות בין איבר $a$ לקבוצה $A$, וסימנו $a\in A$. בקורס שלנו הקבוצות יהיו יחסית פשוטות, ולכן לא ניתקל בקבוצה שאיבריה הם גם קבוצות. זה בהחלט תרחיש אפשרי במתמטיקה (למשל קבוצה של שני ישרים, כאשר כל ישר הוא קבוצת נקודות(, אבל בקורס נעסוק בקבוצות מספרים וקבוצות וקטורים (וקטורים אינם קבוצות(. בכל אופן, ייתכן קשר יותר טבעי בין שתי קבוצות $A,B$.

::: hdef
נאמר ש-$A$ מוכלת ב-$B$ ונסמן $A\subseteq B$ אם כל איבר של $A$ הוא גם איבר של $B$.

באופן קצת יותר מתמטי $A\subseteq B$ אם לכל $a\in A$ מתקיים $a\in B$.

אם ההיפך הוא הנכון, כלומר קיים $a\in A$ עבורו $a\notin B$, אז נסמן $A\nsubseteq B$ ונאמר ש-$A$ לא מוכלת ב-$B$.
:::

::: center
(עיגול בתוך עיגול כדי לתאר הכלה, ושני עיגולים שרק נחתכים כדי לתאר חוסר הכלה(
:::

::: example
עבור $A=\{1,2\},\,B=\{1,2,3\}$ מתקיים $A\subseteq B$ כי גם $1\in B$ וגם $2\in B$. אבל $B\nsubseteq A$ כי $3\in B$ אך $3\notin A$.
:::

::: self
נגדיר $A=\{1,3\},\,B=\{-1,1,2,3\},\,C=\{-1,2\}$. מצאו את כל זוגות הקבוצות שמקיימות קשר של הכלה.
:::

::: hdef
נאמר ששתי קבוצות $A,B$ הן שוות ונסמן $A=B$ אם יש בהן בדיוק אותם האיברים, כלומר מתקיים $x\in A$ אם ורק אם $x\in B$.
:::

::: {.remark}
כדי להוכיח כי $A=B$, הדרך המקובלת היא להוכיח כי $A\subseteq B$ וגם $B\subseteq A$. דרך הוכחה זו נקראת הכלה דו-צדדית.
:::

נסכם את רעיון ההוכחה: מוכיחים שתי הכלות. לכל הכלה מתחילים את הטיעון ביהי כדי להצהיר שבחרנו איבר כללי מתוך הקבוצה הנתונה. אחר כך משתמשים בהגדרת הקבוצה כדי להראות שהאיבר גם מקיים את ההגדרה של הקבוצה השנייה.

::: prop
$\mathbb{N\subseteq\mathbb{Z}\subseteq\mathbb{Q}\subseteq\mathbb{R}\subseteq\mathbb{\mathbb{C}}}$ וכל הקבוצות שונות זו מזו.
:::

::: hproof
ברור כי $\mathbb{N}\subseteq\mathbb{Z}$ לפי הגדרת $\mathbb{Z}$ כהרחבה של $\mathbb{N}$, ורואים שאין שוויון כי $-1\notin\mathbb{N}$. גם דיברנו על ההכלה $\mathbb{Q}\subseteq\mathbb{R}$ שאינה שוויון, כי המספרים הרציונליים הם בדיוק המספרים הממשיים שיש להם הצגה עשרונית שהיא מחזורית החל ממקום מסוים. יש הרבה מספרים ממשיים שאינם כאלה, למשל $\sqrt{2}\notin\mathbb{Q}$.

נוכיח כי $\mathbb{Z}\subseteq\mathbb{Q}$ יהי $n\in\mathbb{Z}$. מתקיים $n=\frac{n}{1}$ וזו מנה של מספרים שלמים, ולכן $n\in\mathbb{Q}$. אז $\mathbb{Z}\subseteq\mathbb{Q}$, ואין שוויון כי למשל $\frac{1}{2}\in\mathbb{Q}$ אך $\frac{1}{2}\notin\mathbb{Z}$.

נוכיח כי $\mathbb{\mathbb{R}}\subseteq\mathbb{\mathbb{C}}$ יהי $x\in\mathbb{\mathbb{R}}$. מתקיים $x=x+0\cdot i$ וזו הצגה של מספר מרוכב, ולכן $x\in\mathbb{C}$. אז $\mathbb{\mathbb{R}}\subseteq\mathbb{\mathbb{C}}$, ואין שוויון כי למשל $i\in\mathbb{C}$ אך $i\notin\mathbb{\mathbb{R}}$.
:::

## 0.4 פעולות בין קבוצות

::: hdef
בהינתן שתי קבוצות $A,B$ נגדיר את הקבוצות הבאות

א. החיתוך $A\cap B$ הוא קבוצת כל האיברים השייכים גם ל-$A$ וגם ל-$B$.

ב. האיחוד $A\cup B$ הוא קבוצת כל האיברים השייכים לפחות לאחת משתי הקבוצות $A,B$.
:::

::: center
(דיאגרמות ון לשתי קבוצות האחת לחיתוך, השנייה לאיחוד עם צבע שונה(
:::

::: {.remark}
במקרה של איחוד זה לא משנה אם האיבר שייך רק לקבוצה אחת או לשתיהן. בכל מקרה הוא נספר רק פעם אחת באיחוד.
:::

::: examples
א. עבור $A=\{1,2,3\},\,B=\{2,3,4\}$ מתקיים  $$.A\cap B=\{2,3\},\,A\cup B=\{1,2,3,4\}$$

ב. מתקיים $\mathbb{R}\cap\mathbb{C}=\mathbb{R},\,\mathbb{R}\cup\mathbb{C}=\mathbb{C}$ כי $\mathbb{R\subseteq\mathbb{C}}$.

ג. נסמן $D=\{n\in\mathbb{N}|n\text{ {is divided by 5}\}}$ $C=\{n\in\mathbb{N}|n\text{ {is divided by 3}\},}$. אז לפי הגדרת החיתוך והעובדה ש-$3,5$ הם מספרים זרים (המחלק המשותף היחיד שלהם הוא $1$(, נובע כי $$.C\cap D=\{n\in\mathbb{N}|n\text{ {is divided by 3 and 5}\}=\{n\ensuremath{\in}\ensuremath{\mathbb{N}}|n\text{ {is divided by 15}\}=\{15,30,45,...\}}}$$

האפיון של האיחוד פחות פשוט: מדובר בקבוצת כל המספרים שמתחלקים ב-$3$, $5$ או בשניהם (כלומר ב-$15$, המקרה של החיתוך(. כך נקבל $$.C\cup D=\{3,5,6,9,10,12,15,18,20,21,24,25,27,30...\}$$
:::

::: self
חשבו את $A\cap B,\,A\cup B$ עבור $A=\{-1,0,1\},\,B=\{-2,0,1,2\}$.
:::

::: prop
לכל שתי קבוצות $A,B$ מתקיים $$.A\cap B\subseteq A\subseteq A\cup B$$
:::

::: hproof
יש כאן שתי הכלות. נוכיח תחילה כי $A\cap B\subseteq A$ יהי $a\in A\cap B$. אז מיידית לפי הגדרת החיתוך מתקיים $a\in A$ ולכן $A\cap B\subseteq A$.

כעת נוכיח כי $A\subseteq A\cup B$. גם כאן זה מיידי כי כל $x\in A$ מקיים את הגדרת האיחוד (בין אם $x\in B$ ובין אם לאו(.
:::

::: {.remark}
באותו אופן (או משיקולי סימטריה( גם מתקיים  $$.A\cap B\subseteq B\subseteq A\cup B$$
:::

## 0.5 תרגילים {#תרגילים .unnumbered}

( הוכיחו כי $$.\{2n-1|n\in\mathbb{Z}\}=\{2m+1|m\in\mathbb{Z}\}$$ ( הוכיחו כי $$.\{z\in\mathbb{C}|\text{{Im}}(z)=2\text{{Re}}(z)\}=\{t+2ti|t\in\mathbb{R}\}$$

( נגדיר $A=\{\frac{1}{n}|n\in\mathbb{Z},\,n\neq0\}$.

א. חשבו את $A\cap\mathbb{Z}$.

ב. הראו כי $A\cup\mathbb{Z\subseteq\mathbb{\mathbb{Q}}}$, אך אין שוויון.
