
# הקדמה {#הקדמה .unnumbered}

::: flushright
:::

אלגברה לינארית היא אחת מאבני היסוד של המתמטיקה המודרנית. בתור התחלה, היא קשורה באופן הדוק לגיאומטריה של המישור וגם לגיאומטריה של המרחב. בחטיבת הביניים לומדים על משוואה בנעלם אחד, וגם על מערכת של שתי משוואות בשני נעלמים. למשל:

 $$\begin{cases}
3x+2y=8\\
x+y=3
\end{cases}$$

יש יותר מדרך אחת לפתור מערכת כזו, כמו להכפיל את המשוואה השנייה ב-$2$ ואז להחסיר אותה מהמשוואה הראשונה. כך מקבלים $x=2$ ולבסוף $y=1$ עי הצבה באחת המשוואות. מבחינה גיאומטרית, כל משוואה מייצגת קו ישר במישור, ופתרון המערכת מוביל לנקודת החיתוך של שני הישרים.

::: center
)הגרפים של שני הישרים עם דגש על נקודת החיתוך(
:::

בבסיסה אלגברה לינארית עוסקת בפתרון מערכת של משוואות לינאריות, כלומר משוואות ממעלה ראשונה במספר נעלמים. בתחומים רבים במדע ובכלל יכולים להופיע הרבה נעלמים והרבה אילוצים )משוואות(, בהתאם למה שידוע לנו על הבעיה הרלוונטית.

::: example
תומר נוסע מאילת צפונה, ואלה נוסעת מתל אביב דרומה. המרחק ההתחלתי ביניהם הוא $350$ קמ. תומר נוסע במהירות $60$ קמש במשך $t_{1}$ שעות, וממשיך במהירות $90$ קמש במשך $t_{2}$ שעות עד שהוא חולף על פני המכונית של אלה ומזהה אותה. עד לרגע זה אלה נסעה במהירות $90$ קמ במשך $t_{3}$ שעות ואחר כך במהירות $110$ קמ במשך $t_{4}$ שעות. אם נשווה בין סכומי זמני התנועה של שתי המכוניות וגם נדרוש שסכום הדרכים יהיה המרחק ההתחלתי, נקבל שתי משוואות בארבעה נעלמים:

 $$\begin{cases}
t_{1}+t_{2}=t_{3}+t_{4}\\
60t_{1}+90t_{2}+90t_{3}+110t_{4}=350
\end{cases}$$

למערכת משוואות לינארית )ממל בראשי תיבות( זו יש אינסוף פתרונות בתחום ההגדרה הרלוונטי של מספרים חיוביים. אם למשל נציב $t_{3}=t_{4}=1$ בשתי המשוואות, נקבל ממל חדשה של שתי משוואות בשני נעלמים:

 $$\begin{cases}
t_{1}+t_{2}=2\\
60t_{1}+90t_{2}=150
\end{cases}$$

אפשר לפתור את הממל הזו כרגיל, אבל קל לבדוק שהפתרון הוא $t_{1}=t_{2}=1$. לכן, אחד הפתרונות של הממל המקורית )בארבעה נעלמים( הוא $t_{1}=t_{2}=t_{3}=t_{4}=1$. אבל זה לא הפתרון היחיד כי בחרנו את הערכים של $t_{3},t_{4}$ באופן שרירותי )נוח לחישובים, אך לא יותר מזה(.

נראה בפרק איך אפשר לכתוב את קבוצת הפתרונות באופן כללי, אבל כבר אפשר להבין שהיא אינסופית כי יש לנו חופש לבחור את ערכי $t_{3},t_{4}$. אמנם לא מדובר בחופש מוחלט כי כל ארבעת הזמנים צריכים להיות חיוביים )מה שמקטין את קבוצת הפתרונות(, אבל עדיין יש פה מספיק חופש לאינסוף פתרונות.

במובן מסוים אפשר לומר שאלה מחליטה בשביל תומר על זמני הנסיעה שלו. זו דרך הסתכלות שרירותית ומאוד טכנית - אפשר לחשוב על פתרון המערכת גם באופן הפוך ולתת את החופש לתומר. בפועל )מחוץ לעולם האלגברי(, תומר ואלה לא שמו לב אחד לשנייה עד לרגע הפגישה המקרית. להם יש מידע מלא על זמני הנסיעה, אבל אנחנו מסתפקים במידע חלקי. אם היו לנו מספיק משוואות נוספות )לפחות שתיים(, היה ניתן להגיע לפתרון המדויק שמתאר את תנועת המכוניות. אבל לא תמיד יש לנו מספיק מידע ונלמד להתייחס לכך בהתאם.
:::



באופן כללי, נשאל את השאלות הבאות:

• כיצד פותרים ממל שבה הרבה נעלמים?

• כיצד פותרים ממל שבה הרבה משוואות?

• האם בכלל קיימים פתרונות לממל? אם כן, אז כמה?

כדי לענות על שאלות כאלו באופן מלא ומסודר, ישמשו אותנו שני מושגים יסודיים: וקטורים ומטריצות. נדחה את ההגדרות שלהם לפרקים הרלוונטיים, אבל לעת עתה מספיק לחשוב עליהם כאובייקטים מתמטיים שבהם מופיעים כמה מספרים. למשל, הזוג הסדור $(x,y)$ של שני מספרים $x$ ו-$y$ הוא וקטור עם שני רכיבים )קוארדינטות(. בחטיבת הביניים ובתיכון ראינו שאפשר לחשוב על זוג כזה כעל נקודה סטטית במישור, אבל בלימודי הפיזיקה יש הסתכלות דינמית על וקטור כאובייקט בעל גודל וכיוון )הדוגמה הקלאסית היא כוח שפועל על גוף(. נראה שאפשר לאמץ את שתי הגישות )סטטית ודינמית( במקביל, כאשר האינטואיציה הפיזיקלית מועילה מאוד אך ממש לא הכרחית להבנת הקורס.

לאחר שנתרגל לוקטורים ומטריצות, נראה שאפשר להסתכל עליהם באופן מופשט )תיאורטי( ולשאול עליהם כל מיני שאלות שלא בהכרח קשורות לממל כזו או אחרת. במתמטיקה, דבר אחד מוביל למשנהו וזה טוב לשמור על ראש פתוח כשלומדים מושגים חדשים. הגישה המופשטת של אלגברה לינארית מאפשרת יישומים מגוונים, גם מחוץ לגיאומטריה ופיזיקה. לטובת הסקרנים, נעסוק קצת בפיזיקה דרך הנדסה בחלק מהיישומים בסוף הספר שחורגים מהקורס עצמו. אבל גם נעסוק ביישומים שקשורים למאגר גדול של נתונים כמו למידת מכונה )IA(.

רבים מכם לומדים חשבון דיפרנציאלי ואינטגרלי במקביל. אפשר לומר שאלגברה לינארית מופיעה בחשבון דיפרנציאלי ואינטגרלי הרבה יותר מאשר להיפך. מושג הנגזרת מוביל לקירוב לינארי של פונקציה נתונה עי פונקציה לינארית שמתארת את הישר המשיק לגרף הפונקציה בנקודה נתונה. בנוסף, הקשר לאלגברה לינארית מתבטא בחישוב שטחים )במישור( ונפחים )במרחב( בעזרת כלי שנקרא דטרמיננטה. נפתח אותו בפרק .

::: center
)ישר משיק בצד אחד, מישור משיק בצד שני(
:::

בספר מופיעות דוגמאות רבות, תרגילים פתורים וגם קישורים לסרטונים. תוכלו לחזור אליו בהמשך התואר ככל שתצטרכו להשתמש באלגברה לינארית.



